# Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic
## numpy functions.


In [42]:
import numpy as np
a=np.random.random([10,1])
print(a)


[[0.63626294]
 [0.04836634]
 [0.98285399]
 [0.73616864]
 [0.50451074]
 [0.55925929]
 [0.5984993 ]
 [0.91572857]
 [0.22794517]
 [0.41936697]]


In [41]:
print(a.mean())

0.37618875247073175


# Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [43]:
import numpy as np
x=np.random.random([20,1])
print(x)

[[0.8381027 ]
 [0.20840986]
 [0.46724104]
 [0.83211858]
 [0.44873758]
 [0.01176042]
 [0.77824943]
 [0.08737817]
 [0.33571973]
 [0.28866241]
 [0.46649228]
 [0.74728603]
 [0.33695825]
 [0.69234948]
 [0.7052047 ]
 [0.32497329]
 [0.33767698]
 [0.15460439]
 [0.45030828]
 [0.18078746]]


In [44]:
print(x.var())

0.0617125743580977


In [11]:
print(x.std())

0.2169972960907073


#Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

In [45]:
import numpy as np
a=np.random.random([10,20])
b=np.random.random([20,25])
print(np.matmul(a,b))

[[3.45677003 4.0606697  4.6532053  3.52380207 3.9988995  3.42115688
  5.24605945 5.33196818 5.22160152 5.89015583 4.02854864 3.5819889
  3.80207918 4.75892626 3.84722981 4.05743292 6.24819737 4.87879799
  4.62580583 4.59208361 5.68182453 6.62426456 4.33044472 5.27204909
  4.91087836]
 [3.72899517 4.61488842 4.82612206 3.74060814 4.54484324 3.3869939
  5.5851495  5.38735462 5.18029916 5.85117137 3.97014814 4.06975263
  3.49611416 5.09308019 3.99482872 4.23725729 6.48857459 5.00445254
  5.11074381 4.68889128 5.95044765 6.96529335 4.43808003 5.0928887
  5.66581832]
 [4.35664004 3.59119723 5.05668354 4.4868064  4.94960985 3.774175
  5.51400193 5.58454984 5.85329968 5.9921731  5.04746942 4.78409795
  4.37736503 6.06339579 4.96060825 5.06720303 7.34780584 6.11279813
  5.23006623 5.71529967 5.39860526 7.16851245 4.7318528  5.59917528
  5.72893015]
 [4.78761371 4.00359683 4.71771131 4.2517145  4.82985677 4.21974319
  5.3683343  5.70665341 6.09200484 6.72037272 4.95345164 4.98254193
  4.5406560

#Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 

In [46]:
import numpy as np
A=np.random.random((10,1))
print(A)
def func(x):
      return (1/(1+np.exp(-x)))
result = np.apply_along_axis(func , 0 , A)
print(result)

[[0.07151571]
 [0.61098267]
 [0.17194668]
 [0.94017083]
 [0.97103752]
 [0.96751201]
 [0.36647632]
 [0.13624633]
 [0.72773646]
 [0.91592555]]
[[0.51787131]
 [0.64816493]
 [0.54288107]
 [0.71913416]
 [0.72532625]
 [0.72462331]
 [0.59060726]
 [0.53400899]
 [0.67430836]
 [0.71421118]]
